// src/pages/home/components/OutstandingPrograms/index.vue
<template>
  <section
    ref="sectionRef"
    class="programs-container"
    @click="closeProgramDetail"
  >
    <!-- 背景图容器 -->
    <div class="background-wrapper">
      <img
        src="/assets/image/OutstandingBackground.png"
        alt="Outstanding Programs"
        class="background-image"
      />
    </div>

    <!-- 内容包装器 -->
    <div class="content-wrapper">
      <div
        :class="[
          'content-inner',
          { 'opacity-100': isVisible, 'opacity-0': !isVisible }
        ]"
      >
        <!-- 标题部分 -->
        <SectionTitle title="Outstanding Programs" fontColor="#fff" />

        <!-- 轮播容器 -->
        <div class="carousel-container">
          <!-- 导航箭头 -->
          <button
            v-if="!selectedProgram"
            class="navigation-arrow prev-arrow"
            @click="prevSlide"
            aria-label="Previous"
          >
            ‹
          </button>

          <div class="carousel-inner">
            <div
              class="carousel-track"
              :style="{ transform: getTrackTransform() }"
            >
              <div
                v-for="program in extendedPrograms"
                :key="program.id"
                class="program-card"
                @click.stop="openProgramDetail(program.originalId)"
              >
                <div class="card-image">
                  <img
                    :src="program.image"
                    :alt="program.title"
                    class="card-image-img"
                  />
                  <div class="university-icon">
                    <img
                      :src="program.icon"
                      :alt="`${program.university} icon`"
                      width="38"
                      height="38"
                    />
                  </div>
                </div>
                <div class="card-content">
                  <h3
                    class="program-title"
                    :style="{
                      color: hoveredElements[`title-${program.id}`] ? '#FF6B35' : '#2E4057'
                    }"
                    @mouseenter="handleMouseEnter(`title-${program.id}`)"
                    @mouseleave="handleMouseLeave(`title-${program.id}`)"
                  >
                    {{ program.title }}
                  </h3>
                  <p
                    class="university-name"
                    :style="{
                      color: hoveredElements[`university-${program.id}`] ? '#FF6B35' : '#3A3E48'
                    }"
                    @mouseenter="handleMouseEnter(`university-${program.id}`)"
                    @mouseleave="handleMouseLeave(`university-${program.id}`)"
                  >
                    {{ program.university }}
                  </p>
                </div>
              </div>
            </div>

            <!-- 详情页面 -->
            <div
              :class="[
                'detail-page',
                { 'active': selectedProgram && !isClosing },
                { 'closing': isClosing }
              ]"
              @click="!isClosing && closeProgramDetail()"
            >
              <div
                v-if="selectedProgram"
                class="detail-page-content"
                @click.stop
              >
                <div class="detail-page-image">
                  <img
                    :src="getSelectedProgram()?.image || ''"
                    :alt="getSelectedProgram()?.title || ''"
                    class="detail-image"
                  />
                </div>
                <div class="detail-page-info">
                  <div>
                    <h2 class="detail-page-title">
                      {{ getSelectedProgram()?.title }}
                    </h2>
                    <p class="detail-page-university">
                      {{ getSelectedProgram()?.university }}
                    </p>

                    <div class="detail-page-info-content">
                      <div class="detail-page-info-grid">
                        <div class="detail-page-info-item">
                          <div class="detail-page-info-label">
                            Degree:
                          </div>
                          <div class="detail-page-info-value">
                            {{ getSelectedProgram()?.duration }}
                          </div>
                        </div>

                        <div class="detail-page-info-item">
                          <div class="detail-page-info-label">
                            Teaching Language:
                          </div>
                          <div class="detail-page-info-value">
                            {{ getSelectedProgram()?.language }}
                          </div>
                        </div>

                        <div class="detail-page-info-item">
                          <div class="detail-page-info-label">
                            Tuition:
                          </div>
                          <div class="detail-page-info-value">
                            {{ getSelectedProgram()?.fee }}
                          </div>
                        </div>
                      </div>
                      <div class="detail-page-reasons-section">
                        <h3 class="detail-page-reasons-title">
                          Recommended Reasons:
                        </h3>
                        <ul class="detail-page-reasons-list">
                          <li
                            v-for="(reason, index) in getSelectedProgram()?.reasons || []"
                            :key="index"
                            class="detail-page-reason-item"
                          >
                            <div class="detail-page-reason-number">
                              {{ index + 1 }}
                            </div>
                            <div class="detail-page-reason-text">
                              {{ reason }}
                            </div>
                          </li>
                        </ul>
                      </div>
                    </div>

                    <div class="detail-page-button">
                      Learn More
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <button
            v-if="!selectedProgram"
            class="navigation-arrow next-arrow"
            @click="nextSlide"
            aria-label="Next"
          >
            ›
          </button>
        </div>

        <!-- 分页点 -->
        <div v-if="!selectedProgram" class="pagination-container">
          <div
            v-for="(_, index) in totalSlides"
            :key="index"
            :class="[
              'pagination-dot',
              { 'active': currentSlide === index }
            ]"
            @click="goToSlide(index)"
            role="button"
            :aria-label="`Go to slide ${index + 1}`"
          />
        </div>
      </div>
    </div>
  </section>
</template>

<script>
import { ref, onMounted, onUnmounted, computed, watch } from 'vue'
import SectionTitle from '../../../../components/SectionTitle.vue'

export default {
  name: 'OutstandingPrograms',
  components: {
    SectionTitle
  },
  setup() {
    const sectionRef = ref(null)
    const isVisible = ref(false)
    const currentSlide = ref(0)
    const selectedProgram = ref(null)
    const hoveredElements = ref({})
    const isClosing = ref(false)
    const totalSlides = 5
    const innerWidth = ref(0)

    // Programs data
    const programs = [
      {
        id: 1,
        title: "Traditional Chinese Medicine(TCM)",
        university: "Nanjing University of Chinese Medicine",
        duration: "Bachelor 5 Years",
        language: "Chinese",
        fee: "RMB 24,000 Per Year",
        image: "/assets/image/OutstandingPrograms1.png",
        icon: "/assets/image/icon1.png",
        reasons: [
          "One of the earliest universities of Traditional Chinese Medicine (TCM) founded in China.",
          'NJUCM has been renowned as "the cradle of China\'s higher education in Chinese Medicine".',
          "WHO Collaborating Centre for Traditional Medicine.",
        ],
      },
      {
        id: 2,
        title: "MBBS (Bachelor of Medicine and Bachelor of Surgery)",
        university: "Chongqing Medical University",
        duration: "Bachelor 6 Years",
        language: "English",
        fee: "RMB 42,000 Per Year",
        image: "/assets/image/OutstandingPrograms2.png",
        icon: "/assets/image/icon2.png",
        reasons: [
          "Internationally recognized medical degree with comprehensive clinical training.",
          "Modern facilities and diverse patient exposure.",
          "Opportunity to learn both Western and Chinese medicine approaches.",
        ],
      },
      {
        id: 3,
        title: "Civil Engineering",
        university: "Northwestern Polytechnical University",
        duration: "Bachelor 4 Years",
        language: "English",
        fee: "RMB 26,000 Per Year",
        image: "/assets/image/OutstandingPrograms3.png",
        icon: "/assets/image/icon3.png",
        reasons: [
          "World-class civil engineering program focusing on sustainable development.",
          "Strong industry connections and modern laboratory facilities.",
          "Excellent career prospects in infrastructure and construction.",
        ],
      },
      {
        id: 4,
        title: "Mechanical Engineering",
        university: "China University of Mining and Technology",
        duration: "Bachelor 4 Years",
        language: "English",
        fee: "RMB 28,000 Per Year",
        image: "/assets/image/OutstandingPrograms4.png",
        icon: "/assets/image/icon4.png",
        reasons: [
          "Comprehensive mechanical engineering education with specializations in robotics.",
          "Strong research focus and industry partnerships.",
          "Modern laboratories with cutting-edge equipment.",
        ],
      },
      {
        id: 5,
        title: "Software Engineering",
        university: "Zhejiang University of Technology",
        duration: "Bachelor 4 Years",
        language: "English",
        fee: "RMB 26,000 Per Year",
        image: "/assets/image/OutstandingPrograms5.png",
        icon: "/assets/image/icon5.png",
        reasons: [
          "Cutting-edge software engineering program with focus on AI and data science.",
          "Industry-aligned curriculum with practical projects and internship opportunities.",
          "Located in Hangzhou, one of China's major tech hubs.",
        ],
      },
    ]

    // 更新窗口宽度
    const updateWidth = () => {
      innerWidth.value = 0.7292 * window.innerWidth
    }

    // 创建扩展的程序列表
    const extendedPrograms = computed(() => {
      const extended = []
      for (let i = 0; i < 100; i++) {
        programs.forEach((program, index) => {
          extended.push({
            ...program,
            id: program.id + i * totalSlides + index,
            originalId: program.id,
          })
        })
      }
      return extended
    })

    // 计算轨道的transform值
    const getTrackTransform = () => {
      const cardWidth = 200
      const gap = (innerWidth.value - 5 * cardWidth) / 4
      const moveDistance = cardWidth + gap
      return `translateX(-${currentSlide.value * moveDistance}px)`
    }

    // 获取选中的程序
    const getSelectedProgram = () => {
      return programs.find((program) => program.id === selectedProgram.value)
    }

    // 处理悬停状态
    const handleMouseEnter = (elementId) => {
      hoveredElements.value = { ...hoveredElements.value, [elementId]: true }
    }

    const handleMouseLeave = (elementId) => {
      hoveredElements.value = { ...hoveredElements.value, [elementId]: false }
    }

    // 轮播控制
    const nextSlide = () => {
      currentSlide.value = (currentSlide.value + 1) % totalSlides
    }

    const prevSlide = () => {
      currentSlide.value = (currentSlide.value - 1 + totalSlides) % totalSlides
    }

    const goToSlide = (index) => {
      currentSlide.value = index
    }

    // 程序详情控制
    const openProgramDetail = (programId) => {
      setTimeout(() => {
        isClosing.value = false
        selectedProgram.value = programId
      }, 100)
    }

    const closeProgramDetail = () => {
      if (!isClosing.value) {
        isClosing.value = true
        setTimeout(() => {
          selectedProgram.value = null
          isClosing.value = false
        }, 600)
      }
    }

    // IntersectionObserver
    onMounted(() => {
      updateWidth()
      window.addEventListener('resize', updateWidth)

      const observer = new IntersectionObserver(
        (entries) => {
          const [entry] = entries
          if (entry.isIntersecting) {
            isVisible.value = true
          }
        },
        { threshold: 0.3 }
      )

      if (sectionRef.value) {
        observer.observe(sectionRef.value)
      }

      return () => {
        if (sectionRef.value) {
          observer.unobserve(sectionRef.value)
        }
      }
    })

    onUnmounted(() => {
      window.removeEventListener('resize', updateWidth)
    })

    return {
      sectionRef,
      isVisible,
      currentSlide,
      selectedProgram,
      hoveredElements,
      isClosing,
      totalSlides,
      innerWidth,
      programs,
      extendedPrograms,
      getTrackTransform,
      getSelectedProgram,
      handleMouseEnter,
      handleMouseLeave,
      nextSlide,
      prevSlide,
      goToSlide,
      openProgramDetail,
      closeProgramDetail
    }
  }
}
</script>

<style lang="less" scoped>
.programs-container {
  position: relative;
  width: 100%;
  padding: 60px 0;
  overflow: hidden;
}

.background-wrapper {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 312px;
  z-index: 1;
}

.background-image {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.content-wrapper {
  position: relative;
  z-index: 2;
}

.content-inner {
  transition: opacity 0.5s ease;
}

.opacity-100 {
  opacity: 1;
}

.opacity-0 {
  opacity: 0;
}

.carousel-container {
  position: relative;
  width: calc(100% - 16vw);
  margin: 0 8vw;
  padding: 0 5.54vw;
}

.carousel-inner {
  position: relative;
  width: calc(100% + 10px);
  margin: 20px -5px;
  padding: 10px 5px;
  overflow-x: hidden;
}

.carousel-track {
  display: flex;
  transition: transform 0.8s cubic-bezier(0.25, 0.46, 0.45, 0.94);
  will-change: transform;
  justify-content: space-between;
  gap: calc((100% - 1000px) / 4);
}

.program-card {
  width: 200px;
  height: 390px;
  border-radius: 10px;
  box-shadow: -2px 0px 4px 0px rgba(190, 190, 190, 0.25),
              2px 2px 4px 0px rgba(190, 190, 190, 0.25);
  overflow: hidden;
  background-color: #fff;
  transition: transform 0.3s ease, box-shadow 0.3s ease;
  cursor: pointer;
  display: flex;
  flex-direction: column;
  flex-shrink: 0;
  z-index: 99;

  &:hover {
    transform: translateY(-5px);
  }
}

.card-image {
  width: 100%;
  height: 236px;
  position: relative;
}

.card-image-img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.university-icon {
  position: absolute;
  bottom: 2px;
  left: 50%;
  transform: translateX(-50%);
  width: 38px;
  height: 38px;
  background-color: white;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.15);
  z-index: 5;

  img {
    object-fit: contain;
  }
}

.card-content {
  padding: 12px;
  text-align: center;
  flex-grow: 1;
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.program-title {
  font-weight: bold;
  font-size: 15px;
  line-height: 20px;
  transition: color 0.3s ease;
  cursor: pointer;
  margin: 0;
}

.university-name {
  font-size: 12px;
  margin: 0;
  transition: color 0.3s ease;
  cursor: pointer;
}

.navigation-arrow {
  position: absolute;
  top: 50%;
  transform: translateY(-50%);
  width: 40px;
  height: 40px;
  border-radius: 50%;
  background-color: white;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.2);
  z-index: 10;
  transition: all 0.3s ease;
  color: #ff6b35;
  font-size: 24px;
  font-weight: bold;
  border: none;
  outline: none;

  &:hover {
    background-color: #f3f4f6;
    transform: translateY(-50%) scale(1.1);
  }

  &:disabled {
    cursor: not-allowed;
  }
}

.prev-arrow {
  left: 0;
}

.next-arrow {
  right: 0;
}

.pagination-container {
  display: flex;
  justify-content: center;
  align-items: center;
  margin-top: 24px;
}

.pagination-dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background-color: #dbdfec;
  margin: 0 5px;
  cursor: pointer;
  transition: all 0.4s ease;

  &.active {
    background-color: #ff6b35;
    border: 3px solid #dbdfec;
    width: 14px;
    height: 14px;
  }
}

// 详情页面样式
.detail-page {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: white;
  border-radius: 12px;
  overflow: hidden;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
  z-index: 200;
  transform: translateX(100%);
  transition: transform 0.6s cubic-bezier(0.25, 0.46, 0.45, 0.94),
              opacity 0.6s cubic-bezier(0.25, 0.46, 0.45, 0.94);
  opacity: 0;
  pointer-events: none;

  &.active {
    transform: translateX(0);
    opacity: 1;
    pointer-events: auto;
  }

  &.closing {
    transform: translateX(100%);
    opacity: 0;
    pointer-events: none;
  }
}

.detail-page-content {
  display: flex;
  height: 100%;
  width: 100%;
  border-radius: 10px;
  background: #ffffff;
  box-sizing: border-box;
  border: 1px solid #dbdfec;
  box-shadow: -5px 0px 10px 0px rgba(190, 190, 190, 0.25),
              5px 5px 10px 0px rgba(190, 190, 190, 0.25);
}

.detail-page-image {
  width: 240px;
  height: 100%;
  position: relative;
  overflow: hidden;
}

.detail-image {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.detail-page-info {
  width: calc(100% - 240px);
  padding: 22px;
  display: flex;
  flex-direction: column;
  justify-content: flex-start;
  height: 100%;
  position: relative;
}

.detail-page-title {
  font-size: 21px;
  font-weight: 600;
  color: #2e4057;
  margin-bottom: 3.5px;
  line-height: normal;
  letter-spacing: normal;
}

.detail-page-university {
  font-size: 18px;
  color: #3a3e48;
  font-weight: 300;
  margin-bottom: 25px;
  line-height: normal;
  letter-spacing: normal;
}

.detail-page-info-content {
  display: flex;
  justify-content: space-between;
  align-items: baseline;
  gap: 16px;
}

.detail-page-info-grid {
  width: 330px;
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.detail-page-info-item {
  display: flex;
  align-items: flex-start;
  flex-direction: column;
  gap: 4px;
}

.detail-page-info-label {
  font-weight: 600;
  color: #2E4057;
  display: flex;
  align-items: center;
  margin-right: 4px;
  font-size: 16.5px;

  &::before {
    content: "";
    display: inline-block;
    width: 6px;
    height: 6px;
    background-color: #ff6b35;
    border-radius: 50%;
    margin-right: 15px;
  }
}

.detail-page-info-value {
  font-weight: 300;
  line-height: normal;
  letter-spacing: normal;
  color: #3a3e48;
  margin-left: 21px;
  font-size: 16.5px;
  font-family: PingFang SC;
}

.detail-page-reasons-section {
  flex-grow: 1;
}

.detail-page-reasons-title {
  font-size: 16.5px;
  font-weight: 600;
  color: #2e4057;
  margin-bottom: 22px;
}

.detail-page-reasons-list {
  list-style: none;
  padding: 0;
  margin: 0 0 16px 0;
}

.detail-page-reason-item {
  display: flex;
  align-items: baseline;
  margin-bottom: 20px;
}

.detail-page-reason-number {
  width: 19.5px;
  height: 19.5px;
  border-radius: 50%;
  background-color: #ff6b35;
  color: #fff;
  display: flex;
  align-items: center;
  justify-content: center;
  margin-right: 12px;
  flex-shrink: 0;
  font-size: 13.5px;
  font-weight: 600;
}

.detail-page-reason-text {
  font-weight: 300;
  line-height: normal;
  letter-spacing: normal;
  color: #3a3e48;
  font-size: 16.5px;
}

.detail-page-button {
  position: absolute;
  bottom: 22px;
  right: 22px;
  width: 110px;
  height: 33px;
  background-color: #ff6b35;
  color: #fff;
  padding: 7.5px 12px;
  border-radius: 4px;
  font-weight: 500;
  text-align: center;
  transition: background-color 0.2s ease;
  font-size: 14px;
  line-height: 18px;
  letter-spacing: normal;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;

  &:hover {
    background-color: #e55a29;
  }
}
</style>

// src/pages/home/components/OutstandingPrograms/index.tsx
"use client";

import { useEffect, useRef, useState } from "react";
import Image from "next/image";
import SectionTitle from "../../../../components/SectionTitle";
import styles from "./index.module.css";

const OutstandingPrograms = () => {
  const sectionRef = useRef<HTMLDivElement>(null);
    const [isVisible, setIsVisible] = useState(false);
    const [currentSlide, setCurrentSlide] = useState(0); // 从0开始
    const [selectedProgram, setSelectedProgram] = useState<number | null>(null);
    const [hoveredElements, setHoveredElements] = useState<{
        [key: string]: boolean;
    }>({});
    const [isClosing, setIsClosing] = useState(false);
    const totalSlides = 5;
    const [innerWidth, setInnerWidth] = useState(0);

    useEffect(() => {
        const updateWidth = () => {
            setInnerWidth(0.7292 * window.innerWidth);
        };

        updateWidth();
        window.addEventListener("resize", updateWidth);

        return () => window.removeEventListener("resize", updateWidth);
    }, []);

    // Programs data
    const programs = [
        {
            id: 1,
            title: "Traditional Chinese Medicine(TCM)",
            university: "Nanjing University of Chinese Medicine",
            duration: "Bachelor 5 Years",
            language: "Chinese",
            fee: "RMB 24,000 Per Year",
            image: "/assets/image/OutstandingPrograms1.png",
            icon: "/assets/image/icon1.png",
            reasons: [
                "One of the earliest universities of Traditional Chinese Medicine (TCM) founded in China.",
                'NJUCM has been renowned as "the cradle of China\'s higher education in Chinese Medicine".',
                "WHO Collaborating Centre for Traditional Medicine.",
            ],
        },
        {
            id: 2,
            title: "MBBS (Bachelor of Medicine and Bachelor of Surgery)",
            university: "Chongqing Medical University",
            duration: "Bachelor 6 Years",
            language: "English",
            fee: "RMB 42,000 Per Year",
            image: "/assets/image/OutstandingPrograms2.png",
            icon: "/assets/image/icon2.png",
            reasons: [
                "Internationally recognized medical degree with comprehensive clinical training.",
                "Modern facilities and diverse patient exposure.",
                "Opportunity to learn both Western and Chinese medicine approaches.",
            ],
        },
        {
            id: 3,
            title: "Civil Engineering",
            university: "Northwestern Polytechnical University",
            duration: "Bachelor 4 Years",
            language: "English",
            fee: "RMB 26,000 Per Year",
            image: "/assets/image/OutstandingPrograms3.png",
            icon: "/assets/image/icon3.png",
            reasons: [
                "World-class civil engineering program focusing on sustainable development.",
                "Strong industry connections and modern laboratory facilities.",
                "Excellent career prospects in infrastructure and construction.",
            ],
        },
        {
            id: 4,
            title: "Mechanical Engineering",
            university: "China University of Mining and Technology",
            duration: "Bachelor 4 Years",
            language: "English",
            fee: "RMB 28,000 Per Year",
            image: "/assets/image/OutstandingPrograms4.png",
            icon: "/assets/image/icon4.png",
            reasons: [
                "Comprehensive mechanical engineering education with specializations in robotics.",
                "Strong research focus and industry partnerships.",
                "Modern laboratories with cutting-edge equipment.",
            ],
        },
        {
            id: 5,
            title: "Software Engineering",
            university: "Zhejiang University of Technology",
            duration: "Bachelor 4 Years",
            language: "English",
            fee: "RMB 26,000 Per Year",
            image: "/assets/image/OutstandingPrograms5.png",
            icon: "/assets/image/icon5.png",
            reasons: [
                "Cutting-edge software engineering program with focus on AI and data science.",
                "Industry-aligned curriculum with practical projects and internship opportunities.",
                "Located in Hangzhou, one of China's major tech hubs.",
            ],
        },
    ];

    // 创建扩展的卡片列表，支持单张切换
    const createExtendedPrograms = () => {
        const extended: any[] = [];
        // 无限循环
        for (let i = 0; i < 100; i++) {
            programs.forEach((program, index) => {
                extended.push({
                    ...program,
                    id: program.id + i * totalSlides + index, // 确保每个卡片都有唯一ID
                    originalId: program.id, // 保留原始ID用于详情页面
                });
            });
        }
        return extended;
    };

    // 计算轨道的transform值 - 每次移动一张卡片的距离
    const getTrackTransform = () => {
        // 每张卡片宽度200px + gap，总共移动的距离
        const cardWidth = 200;
        // 可视区域共5张卡片，间距是动态的，所以gap是动态的
        // 总宽度是100vw-16vw-11.08vw-5.54vw=67.4vw
        // 5张卡片宽度是67.4vw-20px*4=67.4vw-80px
        // 所以每张卡片宽度是(67.4vw-80px)/5=13.48vw-16px
        const gap = (innerWidth - 5 * cardWidth) / 4;
        const moveDistance = cardWidth + gap;
        return `translateX(-${currentSlide * moveDistance}px)`;
    };

    // Observe when section enters viewport
  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        const [entry] = entries;
        if (entry.isIntersecting) {
                    setIsVisible(true);
        }
      },
            { threshold: 0.3 }
    );

    if (sectionRef.current) {
      observer.observe(sectionRef.current);
    }

    return () => {
      if (sectionRef.current) {
        observer.unobserve(sectionRef.current);
      }
    };
  }, []);

    // Handle program selection
    const openProgramDetail = (programId: number) => {
        // 防抖
        setTimeout(() => {
            setIsClosing(false);
            setSelectedProgram(programId);
        }, 100);
    };

    const closeProgramDetail = () => {
        if (!isClosing) {
            setIsClosing(true);
            // 延迟清除selectedProgram，让关闭动画完成
            setTimeout(() => {
                setSelectedProgram(null);
                setIsClosing(false);
            }, 600); // 与CSS动画时间一致
        }
    };

    // Get selected program
    const getSelectedProgram = () => {
        return programs.find((program) => program.id === selectedProgram);
    };

    // 处理悬停状态
    const handleMouseEnter = (elementId: string) => {
        setHoveredElements((prev) => ({ ...prev, [elementId]: true }));
    };

    const handleMouseLeave = (elementId: string) => {
        setHoveredElements((prev) => ({ ...prev, [elementId]: false }));
    };

    // 轮播控制逻辑 - 单张切换
    const nextSlide = () => {
        setCurrentSlide((prev) => (prev + 1) % totalSlides);
    };

    const prevSlide = () => {
        setCurrentSlide((prev) => (prev - 1 + totalSlides) % totalSlides);
    };

    const goToSlide = (index: number) => {
        setCurrentSlide(index);
    };

  return (
        <section
            ref={sectionRef}
            className={styles.programsContainer}
            onClick={closeProgramDetail}
        >
            {/* 背景图容器 - 只占据300px高度 */}
            {/* <div className={styles.backgroundImage}></div> */}

            <div style={{ position: "absolute", top: 0, left: 0, width: "100%", height: "312px", zIndex: 1 }}>
                <Image
                    src="/assets/image/OutstandingBackground.png"
                    alt="Outstanding Programs"
                    fill
                    style={{ objectFit: "cover" }}
                    className={styles.backgroundImage}
                />
            </div>

            {/* 内容包装器 */}
            <div className={styles.contentWrapper}>
                <div
                    className={`${
                        isVisible ? "opacity-100" : "opacity-0"
                    } transition-opacity duration-500`}
                >
                    {/* Heading with decorative squares */}
                    <SectionTitle title="Outstanding Programs" fontColor="#fff" />

                    {/* Carousel */}
                    <div className={styles.carouselContainer}>
                        {/* Navigation Arrows */}
                        {!selectedProgram && (
            <button
                                className={`${styles.navigationArrow} ${styles.prevArrow}`}
                                onClick={prevSlide}
                                aria-label="Previous"
                            >
                                ‹
                            </button>
                        )}

                        <div className={styles.carouselInner}>
                            <div
                                className={styles.carouselTrack}
                                style={{ transform: getTrackTransform() }}
                            >
                                {createExtendedPrograms().map((program) => (
                                    <div
              key={program.id}
                                        className={styles.programCard}
                                        onClick={(e) => {
                                            e.stopPropagation();
                                            openProgramDetail(
                                                program.originalId
                                            );
                                        }}
                                    >
                                        <div className={styles.cardImage}>
                                            <Image
                                                src={program.image}
                                                alt={program.title}
                                                fill
                                                className="object-cover"
                                            />
                                            <div
                                                className={
                                                    styles.universityIcon
                                                }
                                            >
                                                <Image
                                                    src={program.icon}
                                                    alt={`${program.university} icon`}
                                                    width={38}
                                                    height={38}
                                                    className="object-contain"
                                                />
                                            </div>
                                        </div>
                                        <div className={styles.cardContent}>
                                            <h3
                                                className={styles.programTitle}
                                                style={{
                                                    color: hoveredElements[
                                                        `title-${program.id}`
                                                    ]
                                                        ? "#FF6B35"
                                                        : "#2E4057",
                                                    cursor: "pointer",
                                                }}
                                                onMouseEnter={() =>
                                                    handleMouseEnter(
                                                        `title-${program.id}`
                                                    )
                                                }
                                                onMouseLeave={() =>
                                                    handleMouseLeave(
                                                        `title-${program.id}`
                                                    )
                                                }
            >
              {program.title}
                                            </h3>
                                            <p
                                                className={
                                                    styles.universityName
                                                }
                                                style={{
                                                    color: hoveredElements[
                                                        `university-${program.id}`
                                                    ]
                                                        ? "#FF6B35"
                                                        : "#3A3E48",
                                                    cursor: "pointer",
                                                }}
                                                onMouseEnter={() =>
                                                    handleMouseEnter(
                                                        `university-${program.id}`
                                                    )
                                                }
                                                onMouseLeave={() =>
                                                    handleMouseLeave(
                                                        `university-${program.id}`
                                                    )
                                                }
                                            >
                                                {program.university}
                                            </p>
                                        </div>
                                    </div>
          ))}
        </div>

                            {/* 新的详情页面 - 覆盖在carouselInner上 */}
                            <div
                                className={`${styles.detailPage} ${
                                    selectedProgram && !isClosing
                                        ? styles.active
                                        : ""
                                } ${isClosing ? styles.closing : ""}`}
                                onClick={(e) => {
                                    if (!isClosing) {
                                        closeProgramDetail();
                                    }
                                }}
                            >
                                {selectedProgram && (
                                    <div
                                        className={styles.detailPageContent}
                                        onClick={(e) => e.stopPropagation()}
                                    >
                                        <div className={styles.detailPageImage}>
                <Image
                                                src={
                                                    getSelectedProgram()
                                                        ?.image || ""
                                                }
                                                alt={
                                                    getSelectedProgram()
                                                        ?.title || ""
                                                }
                                                fill
                                                className="object-cover"
                                            />
                                        </div>
                                        <div className={styles.detailPageInfo}>
                                            <div>
                                                <h2
                                                    className={
                                                        styles.detailPageTitle
                                                    }
                                                >
                                                    {
                                                        getSelectedProgram()
                                                            ?.title
                                                    }
                                                </h2>
                                                <p
                                                    className={
                                                        styles.detailPageUniversity
                                                    }
                                                >
                                                    {
                                                        getSelectedProgram()
                                                            ?.university
                                                    }
                                                </p>

                                                <div
                                                    className={
                                                        styles.detailPageInfoContent
                                                    }
                                                >
                                                    <div
                                                        className={
                                                            styles.detailPageInfoGrid
                                                        }
                                                    >
                                                        <div
                                                            className={
                                                                styles.detailPageInfoItem
                                                            }
                                                        >
                                                            <div
                                                                className={
                                                                    styles.detailPageInfoLabel
                                                                }
                                                            >
                                                                Degree:
                                                            </div>
                                                            <div
                                                                className={
                                                                    styles.detailPageInfoValue
                                                                }
                                                            >
                                                                {
                                                                    getSelectedProgram()
                                                                        ?.duration
                                                                }
                                                            </div>
                                                        </div>

                                                        <div
                                                            className={
                                                                styles.detailPageInfoItem
                                                            }
                                                        >
                                                            <div
                                                                className={
                                                                    styles.detailPageInfoLabel
                                                                }
                                                            >
                                                                Teaching Language:
                                                               
                                                            </div>
                                                            <div
                                                                className={
                                                                    styles.detailPageInfoValue
                                                                }
                                                            >
                                                                {
                                                                    getSelectedProgram()
                                                                        ?.language
                                                                }
                                                            </div>
              </div>
              
                                                        <div
                                                            className={
                                                                styles.detailPageInfoItem
                                                            }
                                                        >
                                                            <div
                                                                className={
                                                                    styles.detailPageInfoLabel
                                                                }
                                                            >
                                                                Tuition:
                                                            </div>
                                                            <div
                                                                className={
                                                                    styles.detailPageInfoValue
                                                                }
                                                            >
                                                                {
                                                                    getSelectedProgram()
                                                                        ?.fee
                                                                }
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div
                                                        className={
                                                            styles.detailPageReasonsList
                                                        }
                                                    >
                                                        <h3
                                                            className={
                                                                styles.detailPageReasonsTitle
                                                            }
                                                        >
                                                            Recommended Reasons
                                                            :
                                                        </h3>
                                                        <ul
                                                            className={
                                                                styles.detailPageReasonsList
                                                            }
                                                        >
                                                            {getSelectedProgram()?.reasons.map(
                                                                (
                                                                    reason,
                                                                    index
                                                                ) => (
                                                                    <li
                                                                        key={
                                                                            index
                                                                        }
                                                                        className={
                                                                            styles.detailPageReasonItem
                                                                        }
                                                                    >
                                                                        <div
                                                                            className={
                                                                                styles.detailPageReasonNumber
                                                                            }
                                                                        >
                                                                            {index +
                                                                                1}
                                                                        </div>
                                                                        <div
                                                                            className={
                                                                                styles.detailPageReasonText
                                                                            }
                                                                        >
                                                                            {
                                                                                reason
                                                                            }
                                                                        </div>
                                                                    </li>
                                                                )
                                                            )}
                                                        </ul>
                                                    </div>
                                                </div>

                                                <div
                                                    className={
                                                        styles.detailPageButton
                                                    }
                                                >
                                                    Learn More
                                                </div>
                  </div>
                  </div>
                  </div>
                                )}
                  </div>
                </div>
                
                        {!selectedProgram && (
                            <button
                                className={`${styles.navigationArrow} ${styles.nextArrow}`}
                                onClick={nextSlide}
                                aria-label="Next"
                            >
                                ›
                            </button>
                        )}
                    </div>

                    {/* Pagination Dots */}
                    {!selectedProgram && (
                        <div className={styles.paginationContainer}>
                            {Array.from({ length: totalSlides }).map(
                                (_, index) => (
                                    <div
                                        key={index}
                                        className={`${styles.paginationDot} ${
                                            currentSlide === index
                                                ? styles.active
                                                : ""
                                        }`}
                                        onClick={() => goToSlide(index)}
                                        role="button"
                                        aria-label={`Go to slide ${index + 1}`}
                                    />
                                )
                            )}
                        </div>
                    )}
              </div>
      </div>
    </section>
  );
};

export default OutstandingPrograms;
